# This configuration is for testing scenarios where a lot of code issues are purposefully injected into a PR
[pr_code_suggestions]
suggestions_depth = "exhaustive"
enable_suggestion_type_reuse = true
num_code_suggestions_per_chunk = 100
num_best_practice_suggestions = 100
